In [1]:
#Importando pandas e definindo o dataframe

import pandas as pd

df = pd.read_excel("sales_data_with_dates.xlsx")

In [2]:
#Verificando os dados para anlise inicial

df.head(10)

,data_venda,numero_nota,codigo_produto,descricao_produto,codigo_cliente,descricao_cliente,valor_unitario_produto,quantidade_vendida_produto,valor_total,custo_da_venda,valor_tabela_de_preco_do_produto
0,02/07/2023,1,P008,Hidróxido de Potássio,C002,Higiene Pro,95.13,12,1141.56,1004.39,80
1,02/06/2023,2,P009,Amônia,C012,SaúdeVital,87.20,4,348.80,301.47,90
2,27/02/2022,3,P007,Hidróxido de Sódio,C009,Saúde Suprema,81.89,79,6469.31,5458.87,70
3,13/10/2023,4,P004,Metanol,C014,HigiSaúde,42.40,71,3010.40,2486.18,40
4,03/08/2023,5,P008,Hidróxido de Potássio,C013,LimpaFacil,78.92,14,1104.88,922.18,80
5,11/10/2022,6,P003,Etanol,C002,Higiene Pro,24.90,15,373.50,262.04,30
6,26/04/2022,7,P010,Cloro,C001,Limpeza Total,98.84,97,9587.48,7037.60,100
7,13/08/2022,8,P002,Benzeno,C011,HigieneMax,18.25,98,1788.50,1287.71,20
8,10/03/2023,9,P012,Fenol,C014,HigiSaúde,128.14,27,3459.78,1882.75,120
9,10/02/2023,10,P007,Hidróxido de Sódio,C004,Clean & Clear,57.07,8,456.56,274.66,70

In [3]:
#Visualizando os valores nulos

df.isnull().sum()

data_venda                          0
numero_nota                         0
codigo_produto                      0
descricao_produto                   0
codigo_cliente                      0
descricao_cliente                   0
valor_unitario_produto              0
quantidade_vendida_produto          0
valor_total                         0
custo_da_venda                      0
valor_tabela_de_preco_do_produto    0
dtype: int64

In [4]:
#Verificando os tipos primitivos de cada coluna

df.dtypes

data_venda                           object
numero_nota                           int64
codigo_produto                       object
descricao_produto                    object
codigo_cliente                       object
descricao_cliente                    object
valor_unitario_produto              float64
quantidade_vendida_produto            int64
valor_total                         float64
custo_da_venda                      float64
valor_tabela_de_preco_do_produto      int64
dtype: object